title: "Backend Byte"
email: backendbyte.official@gmail.com
timezone: Asia/Dhaka
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: backendbyte
paginate: 30
disqus: 'backendbyte'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: compressed
ganalytics: UA-113961478-1

# Authors
authors:
  backendbyte:
    name: backendbyte
    display_name: backendbyte
    avatar: 'assets/images/sal.png'
    email: backendbyte.official@gmail.com
    web: https://www.backendbyte.com
    twitter: https://twitter.com
    description: ""


# Social
social:
  linkedin: https://www.linkedin.com/company/backend-byte
  facebook: https://www.facebook.com/profile.php?id=100092748197746
  twitter: https://twitter.com/backend-byte

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
